# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Cheater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cheater
  pod 'XYNav'
  pod 'XYInfomationSection'
  pod 'XYUIKit', :path => '/Users/quxiaoyou/Desktop/XYUIKit'
end
