# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Cheater' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cheater
  pod 'XYInfomationSection', :path => '/Users/quxiaoyou/Desktop/XYInfomationSection', branch => "feature/swipe"
  pod 'XYUIKit', :path => '/Users/quxiaoyou/Desktop/XYUIKit'
  pod 'XYNav', :path => '/Users/quxiaoyou/Desktop/XYNav/'
  pod 'XYAlbum', :path => '/Users/quxiaoyou/Documents/github/XYAblum'
end
